### ISSUE TITLE
The nodes are not visible

### ISSUE THREAD

**Issue by motolo** [AIGODLIKE/ComfyUI-BlenderAI-node#117]
I'm testing this splendid addon but unfortunately everything works but the nodes are not loaded :( they are not visible.... I'm on Linux.

**Comment by motolo** [comment]
![Schermata_20240722_200122](https://github.com/user-attachments/assets/1d77b007-4154-4a6a-8187-b25dcb56e850)

**Comment by motolo** [comment]
Parsing Failed: RestoreDetail -> module 'aud' has no attribute 'Device'

**Comment by KarryCharon** [comment]
Shilft + A to add new node.
You should create node tree first like comfyui(web end), then Execute Node Tree.
![QQ_1721887224114](https://github.com/user-attachments/assets/c09f57e2-eede-4c65-8eac-480c015c7b48)

**Comment by KarryCharon** [comment]
> Parsing Failed: RestoreDetail -> module 'aud' has no attribute 'Device'

This may cause by python aud library.

**Comment by motolo** [comment]
Shilft + A to add new node don't work...

**Comment by KarryCharon** [comment]
> Shilft + A to add new node don't work...

Fixed! Try the newset version!

**Comment by JoxJisF** [comment]
The "node" "ComfyUI-CUP" was not included in the Comfy, due to a conflict.

【ComfyUI-CUP】Conflicted Nodes (1)
PreviewAudio [ComfyUI]

![image](https://github.com/user-attachments/assets/92663008-8e38-4f11-9db1-c5323e0f5c3a)

**Comment by KarryCharon** [comment]
@JoxJisF Are you install `ComfyUI-BlenderAI-node` by `git clone https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node --recursive` ? The `--recursive` option is important !

**Comment by leohu1** [comment]
> The "node" "ComfyUI-CUP" was not included in the Comfy, due to a conflict.
> 
> 【ComfyUI-CUP】Conflicted Nodes (1) PreviewAudio [ComfyUI]
> 
> ![image](https://private-user-images.githubusercontent.com/45650798/357082543-92663008-8e38-4f11-9db1-c5323e0f5c3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MjI2ODYsIm5iZiI6MTcyMzgyMjM4NiwicGF0aCI6Ii80NTY1MDc5OC8zNTcwODI1NDMtOTI2NjMwMDgtOGUzOC00ZjExLTlkYjEtYzUzMjNlMGY1YzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE1MzMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMDU4YTk2ZDI1NGNmNDE1Y2ExYWE1YmIyY2ZhZDEzOWJiZTQ4ZmEyMzY5YTQ3ZDNiZGQ5YTY2M2U0YzdiZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QId3NXrrBbaMK_sWHvhnqabJ1az_DKM05ge4y6LMlv8)

the bug is still here, the node PreviewAudio conflict ComfyUI's defult node.

**Comment by leohu1** [comment]
> @JoxJisF Are you install `ComfyUI-BlenderAI-node` by `git clone https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node --recursive` ? The `--recursive` option is important !

I used `--recursive`, the bug is still here
I think it's is related to the code, and not the installation
